language: csharp
dist: xenial
dotnet: 2.1.502
mono: none
env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.1

before_script:
  - dotnet --info
  - dotnet restore

script:
  - build/build.sh run build/build.fsx --target Default
