language: csharp

matrix:
  include:
    - dotnet: 1.1.5
      mono: none
      dist: trusty
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp1.1
    - dotnet: 1.1.5
      mono: none
      dist: trusty
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp1.1
    - dotnet: 2.0.3
      mono: none
      dist: trusty
      env: CONFIGURATION=Debug FRAMEWORK=netcoreapp2.0
    - dotnet: 2.0.3
      mono: none
      dist: trusty
      env: CONFIGURATION=Release FRAMEWORK=netcoreapp2.0

before_script:
  - dotnet --info
  - dotnet restore

script:
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK tests/NSubstitute.Acceptance.Specs/NSubstitute.Acceptance.Specs.csproj
