os: Visual Studio 2015
build: off

environment:
  matrix:
    - Configuration: Debug
      Framework: netcoreapp1.0
    - Configuration: Release
      Framework: netcoreapp1.0

init:
  - dotnet --info

build_script:
  - build.bat Build targets=netstandard1.5 mode=%Configuration%
      
test_script:
  - dotnet test -c %Configuration% -f %Framework% Source/NSubstitute.Acceptance.Specs

after_test:
  - dotnet pack -c %Configuration% Source/NSubstitute

artifacts:
  path: 'Source/NSubstitute/**/*.nupkg'

