os: Visual Studio 2015
build: off

environment:
  matrix:
    - Configuration: Debug
      Framework: netcoreapp1.0
    - Configuration: Release
      Framework: netcoreapp1.0

before_test:
  - dotnet --info

test_script:
  - build/build.bat
